name: Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  base_image:
    strategy:
      matrix:
        codename:
          - bionic
          - focal
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/kde-vnc
          tags: ${{ matrix.codename }}
          path: base
          Dockerfile: base/${{ matrix.codename }}/Dockerfile

  applications:
    needs:
      - base_image
    strategy:
      matrix:
        app:
          - adobe-acrobat
          - firefox
          - motrix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.app }}-vnc
          tags: latest
          path: applications/${{ matrix.app }}

  wine:
    needs:
      - base_image
    strategy:
      matrix:
        codename:
          - bionic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/wine-vnc
          tags: ${{ matrix.codename }}
          path: wine
          Dockerfile: wine/${{ matrix.codename }}/Dockerfile
