---
name: Sync Readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # daily


jobs:
  sync:
    strategy:
      matrix:
        repository:
          - kde-vnc
          - adobe-acrobat-vnc
          - firefox-vnc
          - motrix-vnc
          - wine-vnc
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync
        uses: ms-jpq/sync-dockerhub-readme@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.repository }}
          readme: "./README.md"
